[package]
name = "gdrust_player_controller"
version = "0.1.1"
edition = "2024"
description = "Player controller tools for Rust Godot development"
license = "MIT"
repository = "https://github.com/robotnik-dev/gdrust_kit"
authors = ["Robotnik <robotnik.games@gmail.com>"]
readme = "README.md"
